version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    networks:
      - sparknetwork
    volumes:
      - ~/Desktop/git/Demo:/demo-data
      - ~/Desktop/git/examples:/example-data
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "9000:9000"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    networks:
      - sparknetwork
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50010:50010"
#  deploy:
      # mode global will deploy one datanode per docker swarm node
#      mode: global
    
      
volumes:
  datanode:
  namenode:

networks:
  sparknetwork:
    external:
      name: arakatnetwork