from enum import Enum

class ErrorTypes(Enum):
    NO_ERROR=0
    TASK_TO_INNER_EDGE_ERROR=1
    TASK_INSIDE_TASK_ERROR=2
    NOT_SIBLING_ERROR=3
    CYCLE_IN_GRAPH_ERROR=4
    EMPTY_GRAPH_ERROR=5
    INCOMPATIBLE_EDGE_ERROR=6
    UNDEFINED_EDGE_ERROR=7
    INCOMING_DATAFRAME_COUNT_NOT_MATCH_ERROR=8
    INCOMING_MODEL_COUNT_NOT_MATCH_ERROR=9
    NOT_COMPATIBLE_EDGE_WITH_PIPELINE_ERROR=10
    INCOMPATIBLE_PIPELINE_NODE = 11
    REQUIRES_EXACTLY_ONE_ENTRANCE_NODE_ERROR=12
    NON_LINEAR_PIPELINE_ERROR=13
    CV_ELEMENT_COUNT_NOT_MATCH_ERROR=14
    INCOMPATIBLE_CV_NODE_ERROR=15
    NO_ESTIMATOR_PROVIDED_FOR_CV_ERROR=16
    NO_EVALUATOR_PROVIDED_FOR_CV_ERROR = 17
    SCHEMA_REQUIRED_ERROR=18
    UNSUPPORTED_DATA_TYPE_ERROR=19
    INVALID_SCHEMA_ERROR=20
    NOT_COMPATIBLE_NODES_IN_PIPELINE_ERROR=21
    MODEL_HOLDER_CAN_HOLD_SINGLE_MODEL_ERROR=22
    NO_NODE_IN_PIPELINE_ERROR=23
    EMPTY_SQL_EXPRESSION_ERROR=24
    SPECIAL_REQUIREMENT_NOT_SPECIFIED_ERROR=25